package miniJava.SyntacticAnalyzer;

public enum TokenKind {ID, PUBLIC, PRIVATE, STATIC, VOID, NUM, BINOP, UNOP, ADDITIVEUNARY, ASSIGNMENT,  LPAREN, RPAREN, EOT, CLASS, THIS, RETURN, IF, ELSE, WHILE, TRUE, FALSE, NEW,
	INT, BOOLEAN, LSQBRACK, RSQBRACK, LCURBRACK, RCURBRACK, COMMA, SEMICOLON, DOT, COMMENT, ERROR,/*PA2*/ DISJUNCTION, CONJUNCTION, EQUALITY, RELATIONAL, ADDITIVE, MULTIPLICATIVE, UNARY }

